apiVersion: v1
kind: Pod
metadata:
  name: netshoot-worker1
  annotations:
    k8s.v1.cni.cncf.io/networks: veth-rail1-worker1,veth-rail2-worker1
spec:
  nodeSelector:
    kubernetes.io/hostname: k8sdev-worker
  containers:
    - name: netshoot
      image: nicolaka/netshoot:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - infinity
