kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
  podSubnet: 10.11.0.0/16
  serviceSubnet: 10.12.0.0/16
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: bin/cni
      containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
    - hostPath: bin/cni
      containerPath: /opt/cni/bin
  - role: worker
    extraMounts:
    - hostPath: bin/cni
      containerPath: /opt/cni/bin

