apiVersion: v1
kind: Pod
metadata:
  name: netdebug-worker1
spec:
  nodeSelector:
    kubernetes.io/hostname: k8sdev-worker
  hostNetwork: true
  containers:
    - name: netshoot
      image: nicolaka/netshoot:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - infinity
