apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: veth-rail1-worker1
spec:
  config: '{
      "cniVersion": "1.0.0",
      "type": "host-device",
      "device": "pod-if1",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.0.10/24",
            "gateway": "192.168.0.1"
          }
        ]
      }
    }'
